[package]
name = "calc"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
termion = "1.5.6"
tui = "0.15.0"
unicode-width = "0.1.8"
